// Atribuicão Simples
var a = 5 + 3;
var b = a % 5;
var c = 5 * b ** 2;
var d = 10 - a / 2;
var e = 6 * 2 / d;
var f = b % e + 4 / e;
console.log(`A = 5 + 3`);
console.log(`A =`,a);
console.log();
console.log(`B = A % 5`);
console.log(`B =`,a,`% 5`);
console.log(`B =`,b);
console.log();
console.log(`C = 5 * B ** 2`);
console.log(`C = 5 *`,b,`** 2`);
console.log(`C = 9 * 5`);
console.log(`C =`,c);
console.log();
console.log(`D = 10 - A / 2`);
console.log(`D = 10 -`,a,`/ 2`);
console.log(`D = 10 - 4`);
console.log(`D =`,d);
console.log();
console.log(`E = 6 * 2 / D`);
console.log(`E = 6 * 2 /`,d);
console.log(`E = 12 / 6`);
console.log(`E =`,e);
console.log();
console.log(`F = B % E + 4 / E`);
console.log(`F =`,b,`%`,e,`+ 4 /`,e);
console.log(`F = 1 + 2`);
console.log(`F =`,f);
console.log();